Repository Desbordante/desbordante-core, pull requests merged in 2023-02, with the labels that each got.

#166 Add 'help', 'tests', 'jobs' and 'pybind' options for build script
  CMakeLists.txt
  build.sh
  tests/CMakeLists.txt
Labels: org

#176 Add backend tests paper
  docs/papers/Backend tests - Max Fofanov - 2022 autumn.pdf
Labels: org

#175 Statistics paper
  docs/papers/Statistics - Mikhail Firsov - 2022 autumn.pdf
Labels: org

#173 Add RestoreLineOrder methods for TypoMiner, add const qualifiers
  src/algorithms/typo_miner.cpp
  src/algorithms/typo_miner.h
Labels: chore

#178 Remove build_type option, add debug option
  build.sh
Labels: org

#177 Don't examine the diff context when checking formatting
  .github/workflows/check-codestyle.yml
Labels: org

#181 Update README.md
  README.md
Labels: org

#183 Get correct right neighbor when sorting clusters in hyfd::Sampler
  src/algorithms/hyfd/sampler.cpp
Labels: bug

#182 Don't post LGTM comment in clang-tidy workflow
  .github/workflows/check-codestyle.yml
Labels: org
